### ISSUE TITLE
Is it possible to read an existing grace file (*.agr) using pygrace?

### ISSUE THREAD

**Issue by KylinGuo** [uqfoundation/pygrace#11]
Dear developers, I have many grace files (xmgrace files, in fact) that are generated by other codes. I need to modify these grace file using xmgrace (GUI). Is it possible to read an existing grace file (*.agr) using pygrace? I expect that this will save my a lot of time. Thank you!

**Comment by mmckerns** [comment]
Is this what you were looking for?
```
>>> from pygrace import grace
>>> pg = grace(project='mysaved.agr')
```

If not, then please reopen the ticket.

**Comment by KylinGuo** [comment]
> Is this what you were looking for?
> 
> ```
> >>> from pygrace import grace
> >>> pg = grace(project='mysaved.agr')
> ```
> 
> If not, then please reopen the ticket.

Cool! Thank you!
