### ISSUE TITLE
Question: Is it possible to load previously saved xmgrace file (*.agr) and continue to edit it via pygrace?

### ISSUE THREAD

**Issue by KylinGuo** [uqfoundation/pygrace#13]
I am wondering that if it is possible to load previously saved xmgrace file (*.agr) and continue to edit it via pygrace or not?
Suppose that I have saved xmgrace file that is generated by pygrace or other programs (such as p4vasp, etc.). Here is an example (hello.agr). 
```
from pygrace.project import Project
import numpy as np

# prepare data
x = np.linspace(0, 5, 41)
y = np.exp(-x) * np.sin(x)
data = list(zip(x, y))

# instantiate Project class
project = Project(width=400, height=400, background_color=0, background_fill='off')
graph = project.add_graph()
dataset = graph.add_dataset(data)

# appearance settings
# graph.autoformat()
# graph.set_view(0.10, 0.10, 0.40, 0.40)
# graph.set_labels('Time (second)', 'Aptitude (meter)')
# dataset.legend = 'y=exp(-x) * sin(x)'
# graph.xaxis.tick.inout = 'out'
# graph.yaxis.tick.inout = 'out'
# graph.xaxis.tick.place = 'normal'
# graph.yaxis.tick.place = 'normal'

# save as xmgrace file
project.saveall('hello.agr')
```
However, the xmgrace plot above has to be improved. Now my question is that is it possible load to saved xmgrace file (*.agr) and continue to edit it via pygrace? For example: I would like to load the hello.agr file and run the following codes to improve it.
```
# appearance settings
graph.autoformat()
graph.set_view(0.10, 0.10, 0.40, 0.40)
graph.set_labels('Time (second)', 'Aptitude (meter)')
dataset.legend = 'y=exp(-x) * sin(x)'
graph.xaxis.tick.inout = 'out'
graph.yaxis.tick.inout = 'out'
graph.xaxis.tick.place = 'normal'
graph.yaxis.tick.place = 'normal'
```
I find I could use
```
from pygrace import grace
g = grace(project='hello.agr')
```
to "load" the hello.agr file. But how can I access these objects such as Graph, DataSet, etc?

**Comment by mmckerns** [comment]
@KylinGuo: unfortunately, this doesn't work well currently.  The honest answer is that `pygrace.project` and `pygrace.grace` were two different code bases that were very mildly merged.  The first one cannot currently load an existing `.agr` file, but the second can.  So `g` is an "interactive session", and it's the older code base.

You can get to a `Project` and `Graph` etc like this:
```
>>> g
<pygrace.interactive.session.grace object at 0x1108a0dc0>
>>> g.session
<pygrace.interactive.project.Project object at 0x1108a0d90>
>>> g.session.curr_graph
<pygrace.interactive.project.Graph object at 0x1108a0d30>
```
However, these are the original `Graph` and `Project` objects, and don't have the same (full) interface as you get from `pygrace.project`.

The most common way to configure the "old" code is to use the interactive command interface.
```
>>> pg = g.session.pexec
>>> pg('world xmax 100')
>>> pg('world ymax 1')
>>> pg('xaxis tick major 10')
>>> pg('yaxis tick major .1')
>>> pg('redraw')
```

The "new" `Project` and `Graph` interfaces really should be populated into the "interactive" session, but this hasn't been done.

**Comment by KylinGuo** [comment]
> 

@mmckerns Thank you for your reply! The ``interactive command interface`` is also good for me as it gives me a quick and efficient way to modify the previous saved *.agr file. Here I have a further question that where I could find the full list of commands that ``pg`` could recognized such as ``xaxis tick major 10``, ``redraw`` and so on. Thank you!

**Comment by KylinGuo** [comment]
> > 
> 
> @mmckerns Thank you for your reply! The `interactive command interface` is also good for me as it gives me a quick and efficient way to modify the previous saved *.agr file. Here I have a further question that where I could find the full list of commands that `pg` could recognized such as `xaxis tick major 10`, `redraw` and so on. Thank you!

I know how to play with it now. Just open any *.agr file with text editor and I will get all commands that works.

**Comment by mmckerns** [comment]
That's right.  I'll close this now.  Thanks for the reminder that the code bases need to be better merged. :)
