### ISSUE TITLE
Is there "subplot" in pygrace?

### ISSUE THREAD

**Issue by KylinGuo** [uqfoundation/pygrace#14]
Dear developers, I would like to know it there a simply way to make multi-plot, which looks like the ```subplot``` function does in MATLAB? I use this function in xmgrace via menu. See below. 
<img width="1074" alt="2023-06-02_194528" src="https://github.com/uqfoundation/pygrace/assets/32160749/5886c58b-5900-4b05-941d-a25237c3b664">
At present, I work around it in this way. 
Firstly, I use ```add_graph()``` method of Project to add graph. 
Secondly, I use ```set_view``` method of Graph to set the position of graphs appropriately. 
Here is an example to illustrate what I say. 
```
from pygrace.project import Project
import numpy as np

# prepare data
x = np.linspace(0, 5, 41)
y1 = np.exp(-x) * np.sin(x)
y2 = np.exp(-x) * np.cos(x)
data1 = list(zip(x, y1))
data2 = list(zip(x, y2))
# instantiate Project class
project = Project(width=400, height=400, background_color=0, background_fill='off')
# panel 1
graph1 = project.add_graph()
dataset1 = graph1.add_dataset(data1)
graph1.autoformat()
graph1.set_view(0.10, 0.10, 0.40, 0.40)
# panel 2
graph2 = project.add_graph()
dataset2 = graph2.add_dataset(data2)
graph2.autoformat()
graph2.set_view(0.50, 0.10, 0.80, 0.40)
# save as xmgrace file
project.saveall('hello.agr')
```
<img width="384" alt="2023-06-02_195547" src="https://github.com/uqfoundation/pygrace/assets/32160749/e745cb1b-98f8-4203-aea4-a9dfc9e0a0f7">

Thank you!

**Comment by mmckerns** [comment]
You can see in the example: https://github.com/uqfoundation/pygrace/blob/master/examples/02_multiplot.py
You are doing basically the same thing as expected.

However, there is a way to work with multiple plots at once, it's just a bit tucked away here:
https://github.com/uqfoundation/pygrace/blob/master/pygrace/extensions/multi_plot.py

**Comment by KylinGuo** [comment]
> You can see in the example: https://github.com/uqfoundation/pygrace/blob/master/examples/02_multiplot.py You are doing basically the same thing as expected.
> 
> However, there is a way to work with multiple plots at once, it's just a bit tucked away here: https://github.com/uqfoundation/pygrace/blob/master/pygrace/extensions/multi_plot.py

@mmckerns Thanks for your reply!

**Comment by mmckerns** [comment]
I need to make the extensions more discoverable.  Closing.  Let me know if you have any issues with it.
